name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - run: docker build -t public.ecr.aws/x4t5q0s6/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true public.ecr.aws/x4t5q0s6/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: Environments
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-361134873412
          # Frontend-env.eba-mrekktjy.eu-north-1.elasticbeanstalk.com
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
